name: "Setup Node Environment"
description: "Checks out the repo, sets up Node.js, caches dependencies, and installs them"
runs:
  using: "composite"
  steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Install Node 20
      uses: actions/setup-node@v4
      with: 
        node-version: 20
    - name: Cache Dependencies
      uses: actions/cache@v4
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm ci
      shell: bash

